apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat4me-message-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chat4me-message
  template:
    metadata:
      labels:
        app: chat4me-message
    spec:
      containers:
        - name: chat4me-message
          image: dalcreeper/docker-loris-repo:chat4me-message-0.0.1
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "400Mi"
              cpu: "50m"
            limits:
              memory: "400Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chat4me-message-service
spec:
  selector:
    app: chat4me-message
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chat4me-message-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat4me-message-deploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85